# Generated by Django 4.2.7 on 2023-12-04 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('header', models.BooleanField(default=True, verbose_name='Cabeçalho')),
                ('header_title', models.CharField(max_length=60, verbose_name='Titulo do cabeçalho')),
                ('footer', models.BooleanField(default=True, verbose_name='Rodapé')),
                ('footer_text', models.CharField(max_length=60, verbose_name='Texto do rodapé')),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configurações do site',
            },
        ),
    ]
