# Generated by Django 4.2.7 on 2023-11-28 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('task_text', models.TextField(verbose_name='Tarefa')),
                ('end_in', models.DateTimeField(verbose_name='Terminar em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('finalizado', 'Finalizado')], max_length=100, verbose_name='Status')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
